# Generated by Django 4.0.6 on 2022-07-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_alter_employee_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='role',
            new_name='role_foreign',
        ),
    ]
