# Generated by Django 4.0.6 on 2022-07-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0006_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
