# Generated by Django 4.0.6 on 2022-07-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0007_alter_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='role_foreign',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
    ]
