# Generated by Django 4.0.6 on 2022-07-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0008_rename_role_foreign_employee_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dept',
            new_name='department',
        ),
    ]
